/*
*   MIT License
*
*   Copyright (c) 2020 Mathias Hillmann
*
*   Permission is hereby granted, free of charge, to any person obtaining a copy
*   of this software and associated documentation files (the "Software"), to deal
*   in the Software without restriction, including without limitation the rights
*   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*   copies of the Software, and to permit persons to whom the Software is
*   furnished to do so, subject to the following conditions:
*
*   The above copyright notice and this permission notice shall be included in all
*   copies or substantial portions of the Software.
*
*   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
*   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
*   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
*   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
*   SOFTWARE.
*/
package com.mathiashillmann.sococr;
/**
 *
 * @author Mathias Hillmann
 */
import static com.mathiashillmann.sococr.DadosPorSequencial.DadosPorSequencial;
import static com.mathiashillmann.sococr.RealizarOCR.RealizarOCR;
import static com.mathiashillmann.sococr.SepararAso.SepararAso;
import static com.mathiashillmann.sococr.SepararFC.SepararFC;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import net.sourceforge.tess4j.TesseractException;
import org.apache.commons.lang.StringUtils;
import org.apache.commons.io.FileUtils;

public class Janela extends javax.swing.JFrame {
String destino = null;
    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
        try{
        String destino = CriarPastaTemporaria();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        Fundo = new javax.swing.JPanel();
        jProgressBar = new javax.swing.JProgressBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuPrograma = new javax.swing.JMenu();
        Novo = new javax.swing.JMenuItem();
        AbrirLogs = new javax.swing.JMenuItem();
        jConfigurações = new javax.swing.JMenuItem();
        Saida = new javax.swing.JMenuItem();
        MenuAjuda = new javax.swing.JMenu();
        Ajuda = new javax.swing.JMenuItem();
        Sobre = new javax.swing.JMenuItem();

        fileChooser.setDialogTitle("This is my open dialog");
        fileChooser.setFileFilter(new com.mathiashillmann.sococr.FiltroPDF());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Digitalizador de ASO");
        setBackground(new java.awt.Color(255, 255, 255));

        Fundo.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout FundoLayout = new javax.swing.GroupLayout(Fundo);
        Fundo.setLayout(FundoLayout);
        FundoLayout.setHorizontalGroup(
            FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        FundoLayout.setVerticalGroup(
            FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FundoLayout.createSequentialGroup()
                .addGap(0, 264, Short.MAX_VALUE)
                .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MenuPrograma.setText("Programa");

        Novo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        Novo.setText("Novo...");
        Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoActionPerformed(evt);
            }
        });
        MenuPrograma.add(Novo);

        AbrirLogs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        AbrirLogs.setText("Abrir logs");
        MenuPrograma.add(AbrirLogs);

        jConfigurações.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jConfigurações.setText("Configurações");
        jConfigurações.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConfiguraçõesActionPerformed(evt);
            }
        });
        MenuPrograma.add(jConfigurações);

        Saida.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        Saida.setText("Sair");
        Saida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaidaActionPerformed(evt);
            }
        });
        MenuPrograma.add(Saida);

        jMenuBar1.add(MenuPrograma);

        MenuAjuda.setText("Ajuda");

        Ajuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        Ajuda.setText("Ajuda");
        MenuAjuda.add(Ajuda);

        Sobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        Sobre.setText("Sobre");
        Sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobreActionPerformed(evt);
            }
        });
        MenuAjuda.add(Sobre);

        jMenuBar1.add(MenuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaidaActionPerformed
        UIManager.put("OptionPane.yesButtonText", "Sim");
        UIManager.put("OptionPane.noButtonText", "N\u00e3o");
        final int result = JOptionPane.showConfirmDialog(null, "Voc\u00ea tem certeza que deseja sair?", "Confirmar sa\u00edda", 0);
        if (result == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_SaidaActionPerformed

    private void SobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobreActionPerformed
        JOptionPane.showMessageDialog(null, "Desenvolvido por Mathias Ant\u00f4nio de Oliveira Hillmann", "Sobre", 1);
    }//GEN-LAST:event_SobreActionPerformed

    private void NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            String caminho = file.getAbsolutePath();
            String sequencial = null;
            String RetornoWS = null;
            System.out.println(destino);
            try {
                sequencial = RealizarOCR(caminho);
            } catch (TesseractException | IOException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            try {
                boolean SepararAso = SepararAso(sequencial, caminho, destino);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            try {
                boolean SepararFC = SepararFC(sequencial, caminho, destino);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            try {
                RetornoWS = DadosPorSequencial(sequencial);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            String Codempresa = StringUtils.substringBetween(RetornoWS,"&lt;CODIGOEMPRESA>","&lt;/CODIGOEMPRESA>");
            String Codfuncionario = StringUtils.substringBetween(RetornoWS,"&lt;CODIGOFUNCIONARIO>","&lt;/CODIGOFUNCIONARIO>");
            System.out.println(Codempresa);
            System.out.println(Codfuncionario);
            JOptionPane.showMessageDialog(null, "Pronto");
            
        }
        
    }//GEN-LAST:event_NovoActionPerformed

    private void jConfiguraçõesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConfiguraçõesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jConfiguraçõesActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            JFrame frame = new JFrame("Programa");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.pack();
            frame.setLocationRelativeTo(null);
            new Janela().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AbrirLogs;
    private javax.swing.JMenuItem Ajuda;
    private javax.swing.JPanel Fundo;
    private javax.swing.JMenu MenuAjuda;
    private javax.swing.JMenu MenuPrograma;
    private javax.swing.JMenuItem Novo;
    private javax.swing.JMenuItem Saida;
    private javax.swing.JMenuItem Sobre;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JMenuItem jConfigurações;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JProgressBar jProgressBar;
    // End of variables declaration//GEN-END:variables

    private String CriarPastaTemporaria() throws IOException {
        String path = System.getProperty("java.io.tmpdir");
        path = path+"IntegraSOC\\";
        System.out.println(path);
        File file = new File(path);
        if (!file.exists()) {
            if (file.mkdir()) {
                System.out.println("Directory is created!");
            } else {
                System.out.println("ops");
            }
        } else {
            FileUtils.deleteDirectory(file);
            file.mkdir();
        }
    return null;   
    }
}
